### ISSUE TITLE
Build Task

### ISSUE THREAD

**Issue by ChristopherHaws** [chrisism/VSTS.ChocolateyTools#1]
Hello,

I was wondering if there is a reason that these tasks are only set to be used within Release Management and not in VSTS Build? I have a use case where I could really use these tasks inside of my build.

Thanks!

**Comment by chrisism** [comment]
Hey Christopher,
thanks for checking it out. To be honest, I myself didnt have a usecase where I would use it with the build pipeline. But ofcourse, no problem to just add it. I'll pick it up with a new release.
