### ISSUE TITLE
Choco installPackage -Source parameter

### ISSUE THREAD

**Issue by dviry** [chrisism/VSTS.ChocolateyTools#4]
Hi,

I'd like to install Choco packages hosted on my local NuGet server - so an optional property for the package source would be good, are you still actively updating this Task and is this something you could enhance?

Thanks in advance

**Comment by chrisism** [comment]
Hi, when you mean as in source the -s or -source parameter, then we can add it indeed.
Will pick this up soon.

**Comment by chrisism** [comment]
Issue is now Closed#5 
Added support. Rolling out in marketplace.

**Comment by chrisism** [comment]
#5 
v1.1.0 published in marketplace.
