### ISSUE TITLE
Install tries to use admin privileges

### ISSUE THREAD

**Issue by boojew** [chrisism/VSTS.ChocolateyTools#6]
When running from VSTS, I get 

`System.Management.Automation.RuntimeException: Installation of Chocolatey to default folder requires Administrative permissions. Please run from elevated prompt. Please see https://chocolatey.org/install for details and alternatives if needing to install as a non-administrator. ---> System.Management.Automation.RuntimeException: Installation of Chocolatey to default folder requires Administrative permissions. Please run from elevated prompt. Please see https://chocolatey.org/install for details and alternatives if needing to install as a non-administrator.`

**Comment by chrisism** [comment]
The user which is used to run the vsts agent must have the correct permissions. So if you can switch the user of the agent to an user that is allowed to use that folder it should be solved.

**Comment by chrisism** [comment]
No further changes, closing issue.
